[[dependencies]]
name = "Sam"
url = "https://github.com/SirLich/SirLich.github.io"
version = "fb5c195ba0abd3b814a266efb9b0652883e19a61"
version_lock = "5a0bfc8e714680acbeb29e89bea4d6d8d2ff7889"
destination = "test/test_folder"
source = "content/blog"

[[dependencies]]
name = "Bub"
url = "https://github.com/SirLich/SirLich.github.io"
version_lock = "cf09776b88612ab4afba6cf8034d49fd0a6ba196"
destination = "test/test_full_repo"
